apiVersion: v1 
kind: Namespace
metadata:
  name: first-k8s

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  namespace: first-k8s
  labels:
    app: first-app
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels: 
      name: first
  template:
    metadata:
      labels:
        name: first
      name: second
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 4555